import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

import {
    createComponentModelFromContracts
} from "../apps/studio/src/engine/componentModel.js";

import {
    addBlockToPage,
    createStarterPageModel,
    moveBlock,
    pageModelToComponentModel
} from "../apps/studio/src/engine/blockEngine.js";

import {
    COMPONENT_REGISTRY
} from "../apps/studio/src/engine/componentRegistry.js";

import {
    createDefaultTheme,
    themeToPreviewTokens
} from "../apps/studio/src/engine/themeEngine.js";

import {
    addAssetRecord,
    createAssetRecord,
    createEmptyAssetLibrary,
    createUrlAssetRecord
} from "../apps/studio/src/engine/assetManager.js";

import {
    createHistoryEngine
} from "../apps/studio/src/engine/historyEngine.js";

import {
    createCommand
} from "../apps/studio/src/engine/core/commandManager.js";

import {
    createRelmuaEngine
} from "../apps/studio/src/engine/core/engine.js";

import {
    generateHomeArtifacts
} from "../apps/studio/src/engine/homeGenerator.js";

const ROOT = new URL("../", import.meta.url);

test("Component Model generates public-home.json through the Home Generator", () => {
    const heroContract = {
        id: "hero",
        label: "Hero",
        fields: [
            {
                id: "title",
                label: "Title",
                defaultValue: "RELMUA"
            },
            {
                id: "description",
                label: "Description",
                defaultValue: ""
            },
            {
                id: "displayMode",
                label: "Display",
                defaultValue: "Button"
            },
            {
                id: "hidden",
                label: "Hidden",
                defaultValue: false
            }
        ]
    };
    const featuredContract = {
        id: "featured",
        label: "Featured",
        fields: [
            {
                id: "title",
                label: "Title",
                defaultValue: "Projects"
            },
            {
                id: "description",
                label: "Description",
                defaultValue: ""
            },
            {
                id: "displayMode",
                label: "Display",
                defaultValue: "Link"
            },
            {
                id: "hidden",
                label: "Hidden",
                defaultValue: false
            }
        ]
    };

    const model = createComponentModelFromContracts({
        id: "home",
        title: "Home",
        source: "home-editor",
        contracts: [heroContract, featuredContract],
        componentState: {
            hero: {
                title: "Hello from Studio",
                description: "Generated by Component Model",
                displayMode: "Button",
                hidden: false
            },
            featured: {
                title: "Featured Work",
                description: "Generated section",
                displayMode: "Link",
                hidden: false
            }
        }
    });
    const artifacts = generateHomeArtifacts(model);
    const hero = artifacts.publicHome.sections.find(section => section.id === "hero");
    const featured = artifacts.publicHome.sections.find(section => section.id === "featured-projects");

    assert.equal(hero.title, "Hello from Studio");
    assert.equal(hero.description, "Generated by Component Model");
    assert.equal(featured.title, "Featured Work");
    assert.equal(artifacts.outputs["apps/web/data/public-home.json"], artifacts.publicHome);
});

test("Studio Preview and Public Home import the same Component Renderer", async () => {
    const studioMounts = await read("apps/studio/src/app/studioEditorMounts.js");
    const homeRenderer = await read("apps/web/js/homeRenderer.js");
    const componentRenderer = await read("apps/web/js/componentRenderer.js");

    assert.match(studioMounts, /renderComponentModelPreview/);
    assert.match(studioMounts, /generateHomeArtifacts/);
    assert.match(homeRenderer, /applyHomeComponentModelToDocument/);
    assert.match(homeRenderer, /publicHomeConfigToComponentModel/);
    assert.match(componentRenderer, /export function renderComponentModelPreview/);
    assert.doesNotMatch(studioMounts, /publicHome\.sections\[0\]\.title\s*=/);
});

test("Block Engine creates Page Block Component Property models from the registry", () => {
    const page = createStarterPageModel({
        id: "home",
        title: "Home",
        source: "home-editor",
        pageId: "home"
    });
    const withButton = addBlockToPage(page, "button");
    const moved = moveBlock(withButton, withButton.blocks[0].id, "down");
    const componentModel = pageModelToComponentModel(moved);

    assert.ok(COMPONENT_REGISTRY.some(definition => definition.type === "gallery"));
    assert.ok(COMPONENT_REGISTRY.some(definition => definition.type === "card-grid"));
    assert.equal(moved.schemaVersion, 1);
    assert.ok(moved.blocks.every(block => Array.isArray(block.components)));
    assert.ok(componentModel.components.every(component => Array.isArray(component.children)));
    assert.notEqual(moved.blocks[0].id, page.blocks[0].id);
});

test("Theme, Asset, and History engines are independent foundations", () => {
    const theme = createDefaultTheme();
    const tokens = themeToPreviewTokens(theme);
    const library = addAssetRecord(createEmptyAssetLibrary(), {
        id: "asset-1",
        type: "image",
        name: "hero.png",
        mimeType: "image/png",
        size: 1024,
        createdAt: "2026-07-17T00:00:00.000Z",
        status: "draft"
    });
    const history = createHistoryEngine({
        storage: createMemoryStorage(),
        key: "test-history"
    });
    const engine = createRelmuaEngine({
        history
    });
    let commandState = "before";

    engine.commandManager.execute(createCommand({
        id: "theme.updated",
        label: "Theme changed",
        execute(){
            commandState = "after";
        },
        undo(){
            commandState = "before";
        },
        redo(){
            commandState = "after";
        }
    }));

    assert.equal(tokens.primary, "#19584d");
    assert.equal(library.assets[0].type, "image");
    assert.equal(history.list()[0].label, "Theme changed");
    assert.equal(commandState, "after");
    engine.commandManager.undo();
    assert.equal(commandState, "before");
    engine.commandManager.redo();
    assert.equal(commandState, "after");
});

test("Asset and Page models support free-form creator media without direct Public JSON edits", () => {
    const imageFile = {
        name: "hero.png",
        type: "image/png",
        size: 2048
    };
    const audioFile = {
        name: "theme.mp3",
        type: "audio/mpeg",
        size: 4096
    };
    const image = createAssetRecord(imageFile, new Date("2026-07-17T00:00:00.000Z"));
    const audio = createAssetRecord(audioFile, new Date("2026-07-17T00:00:01.000Z"));
    const url = createUrlAssetRecord("https://relmua.com", "RELMUA", new Date("2026-07-17T00:00:02.000Z"));
    const library = [image, audio, url].reduce(
        (current, asset) => addAssetRecord(current, asset),
        createEmptyAssetLibrary()
    );
    const page = createStarterPageModel({
        id: "home",
        title: "Home",
        source: "home-editor",
        pageId: "home"
    });
    const componentModel = pageModelToComponentModel({
        ...page,
        assets: library.assets,
        settings: {
            bgm: {
                enabled: true,
                assetId: audio.id,
                volume: 0.4,
                loop: true,
                showControl: true
            }
        }
    });

    assert.equal(library.assets.length, 3);
    assert.equal(library.assets.find(asset => asset.id === audio.id).type, "audio");
    assert.equal(library.assets.find(asset => asset.id === url.id).href, "https://relmua.com");
    assert.equal(componentModel.settings.bgm.assetId, audio.id);
    assert.equal(componentModel.assets.length, 3);
});

async function read(path){
    return readFile(new URL(path, ROOT), "utf8");
}

function createMemoryStorage(){
    const data = new Map();

    return {
        getItem(key){
            return data.get(key) || null;
        },
        setItem(key, value){
            data.set(key, value);
        }
    };
}
