export function initCollectionForm(config){
    let editingId=null; const byId=id=>document.getElementById(id);
    const clear=()=>{config.fields.forEach(f=>byId(f.id).value=f.default??"");editingId=null;byId(config.formTitleId).textContent=config.addTitle;byId(config.saveButtonId).textContent="追加";byId(config.cancelButtonId).style.display="none";};
    const values=()=>Object.fromEntries(config.fields.map(f=>[f.key,byId(f.id).value.trim()]));
    const render=()=>{const container=byId(config.listId);container.replaceChildren();const records=config.get()[config.collection].sort((a,b)=>a.order-b.order);if(!records.length){const p=document.createElement("p");p.className="panel-note";p.textContent=config.emptyText;container.append(p);return;}records.forEach(record=>container.append(createItem(record)));};
    const createItem=record=>{const item=document.createElement("article");item.className="management-item";const head=document.createElement("div");head.className="management-item-header";const title=document.createElement("h3");title.textContent=record[config.titleKey]||"無題";const badge=document.createElement("span");badge.className="status-badge";badge.textContent=record.status;head.append(title,badge);const summary=document.createElement("p");summary.className="management-item-summary";summary.textContent=record[config.summaryKey]||"説明なし";const actions=document.createElement("div");actions.className="management-item-actions";[["編集",()=>edit(record)],["上へ",()=>move(record.id,"up")],["下へ",()=>move(record.id,"down")],["削除",()=>remove(record.id)]].forEach(([label,handler])=>{const button=document.createElement("button");button.type="button";button.className="button button-secondary";button.textContent=label;button.addEventListener("click",handler);actions.append(button);});item.append(head,summary,actions);return item;};
    const edit=record=>{editingId=record.id;config.fields.forEach(f=>{const value=record[f.key];byId(f.id).value=Array.isArray(value)?value.join("\n"):value??"";});byId(config.formTitleId).textContent=config.editTitle;byId(config.saveButtonId).textContent="更新";byId(config.cancelButtonId).style.display="inline-block";scrollTo({top:0,behavior:"smooth"});};
    const move=(id,direction)=>{config.move(id,direction);render();};
    const remove=id=>{if(!confirm(config.deleteConfirm))return;config.remove(id);if(editingId===id)clear();render();};
    byId(config.saveButtonId).addEventListener("click",()=>{const data=values();if(!data[config.titleKey]){alert(config.requiredMessage);return;}editingId?config.update(editingId,data):config.add(data);clear();render();});
    byId(config.addButtonId).addEventListener("click",clear);byId(config.cancelButtonId).addEventListener("click",clear);clear();render();
}
