import {
    getBrandSections
} from "../../brand/brandSectionRegistry.js";

import {
    getCreatorSites
} from "../../creators/creatorSiteRegistry.js";

import {
    getModules
} from "../../modules/moduleRegistry.js";

import {
    getSystemSections
} from "../systemSectionRegistry.js";

export function getSystemSettings(){
    return [
        createSetting("brand-name", "Brand name", "RELMUA", "Read only"),
        createSetting("canonical-origin", "Canonical origin", "https://relmua.com", "Used by SEO, OGP, robots, sitemap, and publish checks."),
        createSetting("public-root", "Public source root", "apps/web", "Static public site source."),
        createSetting("dist-root", "Public output root", "dist", "Generated by scripts/build-public.mjs."),
        createSetting("build-command", "Build command", "node scripts/build-public.mjs", "Run before release confirmation."),
        createSetting("deploy-source", "Deploy source", "main / dist", "GitHub Pages must be configured by a human."),
        createSetting("cname", "CNAME", "relmua.com", "Must remain in dist after build."),
        createSetting("admin-boundary", "Admin boundary", "dist/admin must not exist", "Public build must never include Admin.")
    ];
}

export function getRegistrySummary(){
    return {
        brandSections: getBrandSections(),
        creatorSites: getCreatorSites(),
        modules: getModules(),
        systemSections: getSystemSections()
    };
}

function createSetting(id, label, value, description){
    return {
        id,
        label,
        value,
        description
    };
}
